apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ct003-tg2-uf-v2-ingress
  namespace: ct003-tg2-uf-v2
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - tgadev.toruslowcode.com
      secretName: ct003-tg2-uf-v2-tls
  rules:
    - host: tgadev.toruslowcode.com
      http:
        paths:
          - path: /ct003/cg/tg2/v2
            pathType: Prefix
            backend:
              service:
                name: ct003-tg2-uf-generator
                port:
                  number: 443